Import Libraries

In [1]:
import pandas as pd
import plotly.express as px

Load Dataset

In [2]:
df = pd.read_excel("Global_Superstore.xlsx")

Explore Dataset

In [5]:
df.head()
df.info()
df.shape
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

Calculate KPIs

Total Sales

In [6]:
total_sales = df['Sales'].sum()
print("Total Sales:", total_sales)

Total Sales: 12642501.909880001

Total Profit

In [7]:
total_profit = df['Profit'].sum()
print("Total Profit:", total_profit)

Total Profit: 1467457.29128

Top 5 Customers

In [8]:
top_customers = (
    df.groupby('Customer Name')['Sales']
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

top_customers

Customer Name
Tom Ashbrook          40488.07080
Tamara Chand          37457.33300
Greg Tran             35550.95428
Christopher Conant    35187.07640
Sean Miller           35170.93296
Name: Sales, dtype: float64

Sales by Category

In [9]:
sales_category = (
    df.groupby('Category')['Sales']
    .sum()
    .reset_index()
)

fig = px.bar(
    sales_category,
    x='Category',
    y='Sales',
    title='Sales by Category'
)

fig.show()

Profit by Region

In [10]:
profit_region = (
    df.groupby('Region')['Profit']
    .sum()
    .reset_index()
)

fig = px.bar(
    profit_region,
    x='Region',
    y='Profit',
    title='Profit by Region'
)

fig.show()

Top 5 Customers Chart

In [11]:
top_df = top_customers.reset_index()

fig = px.bar(
    top_df,
    x='Customer Name',
    y='Sales',
    title='Top 5 Customers by Sales'
)

fig.show()

An interactive dashboard was developed using Streamlit and Plotly to analyze Global Superstore data. The dashboard provides KPIs such as total sales and profit and allows users to explore sales performance across regions, categories, and top customers through interactive visualizations.